### ISSUE TITLE
cannot load pre-trained model, the parameters'name are not consistent

### ISSUE THREAD

**Issue by wuzhe71** [zijundeng/BDRAR#1]
I cannot load the pre-trained model when run infer.py. There are many mismatched parameters.
For example, in the refine3_h2l module of the BDRAR network, the parameters'name in network is 
################
refine3_h2l.0.weight
refine3_h2l.1.weight
refine3_h2l.1.bias
refine3_h2l.3.weight
refine3_h2l.4.weight
refine3_h2l.4.bias
refine3_h2l.6.weight
refine3_h2l.7.weight
refine3_h2l.7.bias
refine3_l2h.0.weight
refine3_l2h.1.weight
refine3_l2h.1.bias
refine3_l2h.3.weight
refine3_l2h.4.weight
refine3_l2h.4.bias
refine3_l2h.6.weight
refine3_l2h.7.weight
refine3_l2h.7.bias
################

However, in the pre-trained models, the corresponding parameters'name is:
################
refine3_hl.0.weight
refine3_hl.1.weight
refine3_hl.1.bias
refine3_hl.1.running_mean
refine3_hl.1.running_var
refine3_hl.3.weight
refine3_hl.4.weight
refine3_hl.4.bias
refine3_hl.4.running_mean
refine3_hl.4.running_var
refine3_hl.6.weight
refine3_hl.7.weight
refine3_hl.7.bias
refine3_hl.7.running_mean
refine3_hl.7.running_var
refine3_lh.0.weight
refine3_lh.1.weight
refine3_lh.1.bias
refine3_lh.1.running_mean
refine3_lh.1.running_var
refine3_lh.3.weight
refine3_lh.4.weight
refine3_lh.4.bias
refine3_lh.4.running_mean
refine3_lh.4.running_var
refine3_lh.6.weight
refine3_lh.7.weight
refine3_lh.7.bias
refine3_lh.7.running_mean
refine3_lh.7.running_var
################

**Comment by zijundeng** [comment]
Thanks. It is fixed now.
