### ISSUE TITLE
pytorch 0.4 will make error: RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

### ISSUE THREAD

**Issue by Jee-King** [zijundeng/BDRAR#2]
Hi ,
I used pytorch-0.4.0 , python2 will make a error:
RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation.
Use pytorch-0.3 to run normally.

**Comment by Jee-King** [comment]
but infer.py must run in pytorch-0.4 ....

**Comment by zijundeng** [comment]
Hi,
You could cancel the inplace behavior of dropout in the model.py.
Just modify the code 
```
for m in self.modules():
    if isinstance(m, nn.ReLU) or isinstance(m, nn.Dropout):
        m.inplace = True
```
to be
```
for m in self.modules():
    if isinstance(m, nn.ReLU):
        m.inplace = True
```

**Comment by Jee-King** [comment]
Thank you very much!
