### ISSUE TITLE
RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58

### ISSUE THREAD

**Issue by leviome** [zijundeng/BDRAR#3]
At the beginning, I encountered a problem like this:
**"RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation"**
So, I solved it by changing  
```
for m in self.modules():
    if isinstance(m, nn.ReLU) or isinstance(m, nn.Dropout):
        m.inplace = True
```
to be
```
for m in self.modules():
    if isinstance(m, nn.ReLU):
        m.inplace = True
```
But a new problem occurs , "**RuntimeError: cuda runtime error (2) : out of memory at /pytorch/aten/src/THC/generic/THCStorage.cu:58**". 
Can't a single 1080 ti support this model?

**Comment by zijundeng** [comment]
I suggest that you should use a smaller scale size (e.g. 400) in train.py, and do not worry about the performance (it is ok).

**Comment by leviome** [comment]
@zijundeng 
thanks a lot! it runs successfully after I set scale size as 320.

**Comment by zijundeng** [comment]
Hi, I think the scale size is too small (according to my experience, haha). Maybe you could try a larger one such as 384. Good luck.

**Comment by leviome** [comment]
thanks for your suggestions.

**Comment by zijundeng** [comment]
You are welcome.
